baseurl: "/"
encoding: utf-8
paginate: 3
paginate_path: "page:num"
markdown: kramdown
plugins:
  - jekyll-paginate
excerpt_separator: <!--more-->
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
